name: Create Release
run-name: Creating release ${{ inputs.tag_name }}
on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Version name; e.g. 1.0.0; DON''T PUT A V IN FRONT OF IT'
                required: true

concurrency:
    group: ${{ github.repository }}
    cancel-in-progress: true

env:
    VERSION_TAG: ${{ inputs.tag_name }}

jobs:
    validate_input:
        runs-on: ubuntu-latest
        steps:
            - name: Validate tagname
              id: validate_input
              run: |
                  if [[ ${{ env.VERSION_TAG }} =~ ^v ]]; then
                      echo "Tag name should not start with a v"
                      exit 1
                  fi
                  if ! [[ ${{ env.VERSION_TAG }} =~ ^[0-9]\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
                      echo "Version tag does not match the pattern."
                      exit 1
                  fi
    
    create_release:
        runs-on: ubuntu-latest
        needs: validate_input

        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.3

            - name: Build
              run: go build -o ./gh-release -ldflags "-s -w"
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: v${{ env.VERSION_TAG }} Release
                  tag_name: v${{ env.VERSION_TAG }}
                  draft: true
                  generate_release_notes: true
                  target_commitish: ${{ github.sha }}
                  body: "Quick install through bash: `curl -sL https://raw.githubusercontent.com/itsvyle/gh-backup/v${{env.VERSION_TAG}}/.github/workflows/quick-install.sh | bash`"
                  files: |
                    gh-release
